### PR TITLE
Upgrade org.openapitools to 7.8.0

### PR DESCRIPTION
**Pull request by mcruzdev**
Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [ ] Pull Request contains link to the issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mcruzdev** [comment]
I need to investigate a little more to remove the import statement for `@Valid` (jakarta.validation) annotation.

**Comment by mcruzdev** [comment]
Hi @ricardozanini @hbelmiro, was necessary to add `jakarta.validation:jakarta.validation-api` to `resteasy-reactive` profile. 
It would be interesting for us to do a validation using capabilities just like we do with jackson but for bean validation `hibernate-validator`, WDYT?

**Review by hbelmiro — APPROVED** [review]
@mcruzdev many thanks for working on this.

> It would be interesting for us to do a validation using capabilities just like we do with jackson but for bean validation hibernate-validator, WDYT?

Sounds good to me.

> We added as default use-bean-validation as true, I think we need to change it to false and if the user wants to use bean validation, must add a Capability.

Why do you think we need to change it to `false`?

**Comment by mcruzdev** [comment]
> @mcruzdev many thanks for working on this.
> 
> 
> 
> > It would be interesting for us to do a validation using capabilities just like we do with jackson but for bean validation hibernate-validator, WDYT?
> 
> 
> 
> Sounds good to me.
> 
> 
> 
> > We added as default use-bean-validation as true, I think we need to change it to false and if the user wants to use bean validation, must add a Capability.
> 
> 
> 
> Why do you think we need to change it to `false`?

Hi @hbelmiro, it depends haha

Combining the capability rule with use-bean-validation true as default we will break some users.

Turning it to false, the user needs to specify and add the hibernate-validator... the my answer is yes (change use bean validation to false by default)

**Comment by hbelmiro** [comment]
> > @mcruzdev many thanks for working on this.
> > > It would be interesting for us to do a validation using capabilities just like we do with jackson but for bean validation hibernate-validator, WDYT?
> > 
> > 
> > Sounds good to me.
> > > We added as default use-bean-validation as true, I think we need to change it to false and if the user wants to use bean validation, must add a Capability.
> > 
> > 
> > Why do you think we need to change it to `false`?
> 
> Hi @hbelmiro, it depends haha
> 
> Combining the capability rule with use-bean-validation true as default we will break some users.
> 
> Turning it to false, the user needs to specify and add the hibernate-validator... the my answer is yes (change use bean validation to false by default)

I see. But I don't think we can default it to false. See this comment: https://github.com/quarkiverse/quarkus-openapi-generator/pull/746#pullrequestreview-2221411151
I think it's ok a small compatibility break in this case. The solution will be quite simple (add the dependency).

**Comment by mcruzdev** [comment]
@hbelmiro makes sense!

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
