### PR TITLE
Upgrade org.openapitools to 7.7.0

### PR DESCRIPTION
**Pull request by mcruzdev**
Many thanks for submitting your Pull Request :heart:!

Fixes #739 build.

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [ ] Pull Request contains link to the issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mcruzdev** [comment]
Hi @ricardozanini, the new version is converting camel case to snake case on `toEnumVarName` (super), when the value is `/status/addressStatus`, the following conversion happen:

`/status/addressStatus` > `/STATUS/ADDRESS_STATUS` > `SLASH_STATUS_SLASH_ADDRESS_STATUS`.

But the expected is:
`SLASH_STATUS_SLASH_ADDRESSSTATUS`.

**Review by ricardozanini — APPROVED** [review]

**Comment by mcruzdev** [comment]
Hi @fjtirado, in the past we talked about how it would be better to avoid rewriting the super method too much, but I see that whenever it changes it could break our override method (it happened now). It's worth it now not to call the super anymore and not depend directly. WDYT @ricardozanini @fjtirado @hbelmiro

**Review by hbelmiro — APPROVED** [review]

**Comment by ricardozanini** [comment]
@mcruzdev can you solve the conflicts?

**Comment by mcruzdev** [comment]
> @mcruzdev can you solve the conflicts?

Solved!

**Comment by fjtirado** [comment]
> Hi @ricardozanini, the new version is converting camel case to snake case on `toEnumVarName` (super), when the value is `/status/addressStatus`, the following conversion happen:
> 
> `/status/addressStatus` > `/STATUS/ADDRESS_STATUS` > `SLASH_STATUS_SLASH_ADDRESS_STATUS`.
> 
> But the expected is: `SLASH_STATUS_SLASH_ADDRESSSTATUS`.

Why ADRESS_STATUS is not valid for us? Because of backward compatibility?

**Comment by mcruzdev** [comment]
> > Hi @ricardozanini, the new version is converting camel case to snake case on `toEnumVarName` (super), when the value is `/status/addressStatus`, the following conversion happen:
> > `/status/addressStatus` > `/STATUS/ADDRESS_STATUS` > `SLASH_STATUS_SLASH_ADDRESS_STATUS`.
> > But the expected is: `SLASH_STATUS_SLASH_ADDRESSSTATUS`.
> 
> Why ADRESS_STATUS is not valid for us? Because of backward compatibility?

Yes @fjtirado!

**Comment by ricardozanini** [comment]
@mcruzdev why did you close the PR?

**Comment by mcruzdev** [comment]
> @mcruzdev why did you close the PR?

I deleted the fork 😆 and recreated it.

**Comment by mcruzdev** [comment]
I replaced this pull request on this #771

**Pull request closed without merging**
