### PR TITLE
#693 - Allow YAML for Server Generation

### PR DESCRIPTION
**Pull request by lizzyTheLizard**
Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

I have added the possibility to use YAML Specifications for server side. As Apicurio only supports JSON, YAML-Files are converted to JSON on the fly. As the documentation for server-side was quite wrong, I changed it accordingly, even though there is already another PR https://github.com/quarkiverse/quarkus-openapi-generator/pull/689 fixing #686 open that will be redundant now.

While handling this, I directly added the possibility to change the base folder. Up to now, all specs are taken from 'resources/openapi', now you can overwrite this with a property as hinted incorrectly by the docs. => This is not directly related to #693, but I thought that property document the current state. I hope it is fine that I added this to this PR directly.

### CODE REVIEW

**Comment by lizzyTheLizard** [comment]
Hi @hbelmiro! I did not understand how the integration-tests were triggered, not this should be fixed...

**Comment by hbelmiro** [comment]
@lizzyTheLizard they need to be manually started by one of the maintainers in the contributor’s first PR. 

@ricardozanini is this approval really needed? We could be more agile by removing it.

**Comment by carlesarnal** [comment]
> > @lizzyTheLizard they need to be manually started by one of the maintainers in the contributor’s first PR.
> > @ricardozanini is this approval really needed? We could be more agile by removing it.
> 
> This is needed for security reasons for first time contributors

Yes, I agree it makes sense having them, we have them in Apicurio as well.

**Review by carlesarnal — APPROVED** [review]

**Comment by ricardozanini** [comment]
@lizzyTheLizard can u rebase?

**Comment by lizzyTheLizard** [comment]
@ricardozanini: Done

**Pull request merged**
