### PR TITLE
fix(): missing @JsonCreator annotation for inner enum

### PR DESCRIPTION
**Pull request by Leibnizhu**
No code changes, but only modified template for enum.

### CODE REVIEW

**Comment by ricardozanini** [comment]
Thank you! 
Do you mind running this patch locally and verify this error?

```
Caused by: java.lang.IllegalArgumentException: Unexpected value 'AVAILABLE'
	at org.acme.petstore.model.Pet$StatusEnum.fromValue(Pet.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:117)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:171)
	... 97 more
```

We have an openAPI with enums already in the test cases that you can use to verify your change.

**Comment by Leibnizhu** [comment]
@ricardozanini :

`WiremockPetStore` has been fixed.  

Notice that `Pet.status` is defined in openapi as lowercase enum : 

```json
"status": {
            "type": "string",
            "description": "pet status in the store",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
``` 

but in `io.quarkiverse.openapi.generator.it.WiremockPetStore`, `status` in response for `GET /pet/1234` was uppercase (before my fix commit ): 

```java
        wireMockServer.stubFor(get(urlEqualTo("/pet/1234"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withHeader("Content-Type", "application/json")
                        .withBody(
                                "{" +
                                        "\"name\": \"Bidu\"," +
                                        "\"status\": \"available\"" +
                                        "}")));
```

**Comment by ricardozanini** [comment]
@Leibnizhu thanks! But please, revert the test and modify the `fromValue` method to do the comparison using `equalsIgnoreCase` instead.

**Comment by Leibnizhu** [comment]
@ricardozanini got it.

**Comment by ricardozanini** [comment]
@all-contributors please add @Leibnizhu for code

**Pull request merged**
