### PR TITLE
issue-496 make the code consistent with documentation and improve test

### PR DESCRIPTION
**Pull request by aecc**
Fixes [https://github.com/quarkiverse/quarkus-openapi-generator/issues/496](https://github.com/quarkiverse/quarkus-openapi-generator/issues/496)

### CODE REVIEW

**Comment by hbelmiro** [comment]
The tests are failing @aecc.

**Comment by aecc** [comment]
I have strong doubts the failing test is related to any of my code:
`/home/runner/work/quarkus-openapi-generator/quarkus-openapi-generator/integration-tests/security/target/generated-sources/open-api-yaml/org/acme/openapi/weather/customsecurity/api/CurrentWeatherDataWithCustomSecurityApi.java:[27,71] class, interface, or enum expected`
however I'll take a better look tomorrow.

**Review by ricardozanini — APPROVED** [review]

**Review by hbelmiro — APPROVED** [review]
Thank you @aecc ❤️

**Comment by hbelmiro** [comment]
https://github.com/all-contributors please add @aecc for code
https://github.com/all-contributors please add @aecc for test

**Comment by hbelmiro** [comment]
@all-contributors please add @aecc for code
@all-contributors please add @aecc for test

**Comment by hbelmiro** [comment]
@all-contributors please add @aecc for code

**Pull request merged**
