### PR TITLE
fixes: getResource puts a leading slash before the disk name on Windows

### PR DESCRIPTION
**Pull request by chberger**
@hbelmiro please find attached my PR for issue https://github.com/quarkiverse/quarkus-openapi-generator/issues/267

### CODE REVIEW

**Comment by ricardozanini** [comment]
@chberger is this error only on the test case or it's a problem in general with the module? I think we need not to swallow this exception.

**Comment by chberger** [comment]
@ricardozanini This is the behavior of ``io.swagger.v3.parser.OpenAPIV3Parser``, so nothing we can fix. However, they return a ``SwaggerParseResult´´ containing some error data.

**Review by hbelmiro — APPROVED** [review]
Many thanks for this contribution, @chberger.
LGTM

**Review by ricardozanini — APPROVED** [review]

**Comment by hbelmiro** [comment]
Cherry-picked to main branch: https://github.com/quarkiverse/quarkus-openapi-generator/pull/269

**Comment by hbelmiro** [comment]
> > @ricardozanini This is the behavior of `io.swagger.v3.parser.OpenAPIV3Parser`, so nothing we can fix. However, they return a ``SwaggerParseResult´´ containing some error data.
> 
> 
> 
> Thank you! Well, I think we should throw an exception if `SwaggerParseResult` contains error data. Not in this PR, thou. @hbelmiro wdyt? We should halt in Compile/Build time since it can be too late to find an error in the openapi definition.

@ricardozanini I agree with you.

**Comment by ricardozanini** [comment]
Can you open an issue to track this?

**Comment by ricardozanini** [comment]
@allcontributors please add @chberger for code

**Comment by chberger** [comment]
> Can you open an issue to track this?

@ricardozanini I've analyzed the issue once more. It's something which needs to be fixed upstream (io.swagger.parser.v3:swagger-parser). Nothing we can do ... Even the ``SwaggerParseResult`` containing the error gets swallowed and we have no chance to react to it :-(

So I would suggest to raise an issue at the Swagger project.

**Comment by ricardozanini** [comment]
Hmmm last time I could infer in their parser. I'll take a look once I get the time. THat's a real shame to have such errors swallowed by the underlying library.

**Comment by chberger** [comment]
That's the affected code:

```
package io.swagger.parser;

import io.swagger.v3.parser.core.extensions.SwaggerParserExtension;
import io.swagger.v3.parser.core.models.AuthorizationValue;
import io.swagger.v3.parser.core.models.ParseOptions;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import io.swagger.v3.parser.OpenAPIV3Parser;

import java.util.List;

public class OpenAPIParser {
    public SwaggerParseResult readLocation(String url, List<AuthorizationValue> auth, ParseOptions options) {
        SwaggerParseResult output = null;

        for(SwaggerParserExtension extension : OpenAPIV3Parser.getExtensions()) {
            output = extension.readLocation(url, auth, options);
            if(output != null && output.getOpenAPI() != null) {
                return output;
            }
        }

        return output;
    }
```

The variable output `` output = extension.readLocation(url, auth, options);`` points to the ``SwaggerParseResult`` which contains the error. However, in the loop the condition ``if(output != null && output.getOpenAPI() != null)`` isn't true cause ``output.getOpenAPI()`` is null and cause we have a 2nd iteration they overwriting the output instance within the next execution...

IMHO definitely something we have to report upstream ..

**Comment by ricardozanini** [comment]
Yes, I agree. We are using a somewhat old version. Maybe they've fixed this in new releases. Feel free to open an issue there. :D

**Comment by chberger** [comment]
I've tested it with the latest version of ``openapitools 6.4.0`` which depends on the latest ``openapi-parser``:

It seems the behavior has changed, at least I've got a ``Nullpointer`` and the test failed:
```
java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.OpenAPI.getExtensions()" because "openAPI" is null
```
I could open a PR to bump the ``openapitools`` version. Only little changes are required (the models from the ``skip-validation`` test have some proper names now instead of  ``InlineObjectXX``. Anyway, haven't anaylzed it further..)

@hbelmiro wdyt?

**Comment by ricardozanini** [comment]
That's a great idea. Let's upgrade it.

**Comment by chberger** [comment]
> That's a great idea. Let's upgrade it.

https://github.com/quarkiverse/quarkus-openapi-generator/pull/273

**Pull request merged**
