### PR TITLE
Import org.eclipse.microprofile.rest.client.annotation.RegisterProvider when custom-register-providers is used

### PR DESCRIPTION
**Pull request by YassinHajaj**
There is a bug actually in the released 0.11.0.
I'll still need to write / correct a few tests for this.

### CODE REVIEW

**Comment by ricardozanini** [comment]
Thank you @YassinHajaj. Now your comment on the other issue makes more sense. Indeed is a case that we didn't anticipate.

**Comment by YassinHajaj** [comment]
Hey @ricardozanini ,
You're welcome :) I think the PR is ready now.
By the way, do you have any idea when we can expect the 0.12.0 ?
If there's anything else I can help with, don't hesitate

**Comment by hbelmiro** [comment]
> I believe we can release it after this PR is merged. cc @hbelmiro wdyt?

I agree @ricardozanini.

**Review by hbelmiro — APPROVED** [review]
LGTM.

**Comment by ricardozanini** [comment]
@all-contributors please add @YassinHajaj for code

**Pull request merged**
