### PR TITLE
Add property additional-properties-as-attribute configuration 

### PR DESCRIPTION
**Pull request by mcruzdev**
Fixes: https://github.com/quarkiverse/quarkus-openapi-generator/issues/442

When Jackson try to serialize/deserialize using a class that inherit of `HashMap`, there are some issues.

On deserialization throws `MismatchInputException` and on serialization does not get plain fields.

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mcruzdev** [comment]
Hi @ricardozanini, @hbelmiro, can you review this pull request?

**Comment by hbelmiro** [comment]
> Edit: I forgot the documentation, could I add the documentation in `/docs/*`?

@mcruzdev Yes, and add a link to that in README.md, please.

**Review by hbelmiro — COMMENTED** [review]
Thank you @mcruzdev. Looks pretty good.
I left two comments and I'll wait for the docs.

**Comment by mcruzdev** [comment]
> Thank you @mcruzdev. Looks pretty good. I left two comments and I'll wait for the docs.

Hi, I updated the `.qute` file and added the docs. I got as example this open pull request #493.

**Review by ricardozanini — APPROVED** [review]

**Comment by hbelmiro** [comment]
Just waiting for @ayhanap's [validation](https://github.com/quarkiverse/quarkus-openapi-generator/issues/442#issuecomment-1743007373) before merging.

**Pull request merged**
